name: Test & Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        
      - run: dotnet restore

      - name: Test Run
        run: dotnet test Radon.AppTest/Radon.AppTest.csproj
 
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCHER_TOKEN }}
          repository: RhyVis/RadonBuild
          event-type: build_trigger
          client-payload: '{"sha": "${{ steps.short-sha.outputs.sha }}"}'
